export interface BetterCallInterface {
    assert(...args):any;
    clear():any;
    count(label?:string):any;
    countReset(label?:string):any;
    debug(...args):any;
    dir(obj:object):any;
    dirxml(obj:object):any;
    error(...args):any;
    group(label?:string):any;
    groupCollapsed(label?:string):any;
    groupEnd(n?:number):any;
    info(...args):any;
    log(...args):any;
    table(data:Array<any>|object,name?:string,columns?:any[]):any;
    time(label:string):any;
    timeEnd(label:string):any;
    timeLog(label:string):any;
    timeStamp(label?:string):any;
    trace(...args):any;
    warn(...args):any;
}